// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV4keZLneZ7UG6Wai4qMTKcg4v_8T1OTc',
    appId: '1:598100330134:web:99a9770bcc701021a624b7',
    messagingSenderId: '598100330134',
    projectId: 'tunex-e612d',
    authDomain: 'tunex-e612d.firebaseapp.com',
    storageBucket: 'tunex-e612d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxWj9m5JblakbaiG8brDwkEnjrCmMlGhM',
    appId: '1:598100330134:android:ca2ee3b48d168037a624b7',
    messagingSenderId: '598100330134',
    projectId: 'tunex-e612d',
    storageBucket: 'tunex-e612d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADRTQuPPHP-T2MIZilaU_IxzEYEYuVyBo',
    appId: '1:598100330134:ios:6a0b30daaf2bf594a624b7',
    messagingSenderId: '598100330134',
    projectId: 'tunex-e612d',
    storageBucket: 'tunex-e612d.firebasestorage.app',
    iosBundleId: 'com.example.tunex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADRTQuPPHP-T2MIZilaU_IxzEYEYuVyBo',
    appId: '1:598100330134:ios:6a0b30daaf2bf594a624b7',
    messagingSenderId: '598100330134',
    projectId: 'tunex-e612d',
    storageBucket: 'tunex-e612d.firebasestorage.app',
    iosBundleId: 'com.example.tunex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV4keZLneZ7UG6Wai4qMTKcg4v_8T1OTc',
    appId: '1:598100330134:web:57dc6cb111dc7bdaa624b7',
    messagingSenderId: '598100330134',
    projectId: 'tunex-e612d',
    authDomain: 'tunex-e612d.firebaseapp.com',
    storageBucket: 'tunex-e612d.firebasestorage.app',
  );
}
